version: '3.9'

services:
  # React App Service
  react_app:
    build: ./client
    ports: 
      - 5173:5173
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./react_app:/react_app
      - /react_app/node_modules

  # MongoDB Service
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node API Service
  api:
    build: ./server
    ports:
      - 3000:3000
    env_file:
      - ./server/.env
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
