export const userRouteVariables = {
    Home: "/",
    NotFound: "*",
    Jobs: "/jobs",
    Job: "/jobs/:id",
    Laborers: "/laborers",
    Laborer: "/laborers/:id",
    Account: "/account",
    Profile: "/profile",
    Subscription: "/manage-subscription",
    Success: "/success",
    Cancel: "/cancel",
    Notifications: "/notifications",
    PostJob: "/jobs/post-job",
    ListedJobs: "/jobs/listed-jobs",
    ListedJob: "/jobs/listed-jobs/:id",
    Applicants: "/jobs/view-applicants",
    WorksHistory: "/jobs/works-history",
    Chats: "/chats",
    Chat: "/chat/:id/:username",
    LaborerProfile: "/laborer-profile",
    Form: "/become-laborer-form",
    Login: "/login",
    SignUp: "/sign-up",
    Email: "/verify-email",
    OTP: "/verify-otp",
    Password: "/reset-password",
};

export const adminRouteVariables = {
    Dashboard: "/",
    Users: "/users",
    User: "/users/:id",
    Requests: "/laborer-requests",
    Request: "/laborer-requests/view-request-details/:id",
    Plans: "/subscription-plans",
    AddPlan: "/subscription-plans/add-plan",
    EditPlan: "/subscription-plans/edit-plan/:id",
    Subscriptions: "/subscriptions",
    Banners: "/banners",
    AddBanner: "/banners/add-banner",
    EditBanner: "/banners/edit-banner/:id",
    Notofications: "/notifications",
    Login: "/login",
    NotFound: "/*",
};
