name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add PEM File
      run: |
        echo "${{ secrets.EC2_PEM_FILE }}" > ~/.ssh/TaskTrackPemFile.pem
        chmod 600 ~/.ssh/TaskTrackPemFile.pem

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/TaskTrackPemFile.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-200-252-3.ap-south-1.compute.amazonaws.com << 'EOF'
          sudo su - tasktrack
          cd Second-Project/TaskTrack/
          git pull origin main
          npm install
          pm2 restart server
        EOF
