name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machines provided by GitHub Actions

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: SSH Setup (replace with your actual setup)
        uses: actions/checkout@v3  # Fetch SSH key and configuration (details below)
        with:
          persist-credentials: true  # Keep SSH key for subsequent steps

      - name: Connect to Server (replace with your server details)
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ubuntu@ec2-13-200-252-3.ap-south-1.compute.amazonaws.com

      - name: Switch User (adjust as needed)
        run: sudo su - tasktrack

      - name: Navigate to Project Directory
        run: cd Second-Project/TaskTrack/

      - name: Pull Code Updates
        run: git pull origin main

      - name: Install Dependencies
        run: npm install

      - name: Restart Server with PM2
        run: pm2 restart server
