name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-200-252-3.ap-south-1.compute.amazonaws.com << 'EOF'
          sudo su - tasktrack
          cd Second-Project/TaskTrack/
          git pull origin main
          npm install
          pm2 restart server
        EOF
