name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: tasktrack
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
        
        # Sync code to the remote server
        rsync -avz -e "ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./ $USER@$HOST:/home/$USER/Second-Project/TaskTrack

        # Execute deployment commands on the remote server
        ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd /home/tasktrack/Second-Project/TaskTrack
          git pull origin main
          npm install
          pm2 restart all  # Restart the application using pm2
        EOF
