name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machines provided by GitHub Actions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Add your SSH key to GitHub secrets

      - name: Verify SSH Key
        run: ssh-add -L  # List added SSH keys to verify

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-200-252-3.ap-south-1.compute.amazonaws.com << 'EOF'
            sudo su - tasktrack
            cd Second-Project/TaskTrack/
            git pull origin main
            npm install
            pm2 restart server
          EOF
